language: node_js

node_js:
  - 7

script:
  - npm run lint
  - npm run build

after_success:
  # If the build was triggered by a tag, publish the new version
  - 'if [[ $TRAVIS_TAG == v* ]]; then vsce publish -p $VSCE_TOKEN; fi'
